library(DNABarcodes)
library(data.table)

# Import barcode candidates.
# Remove empty rows generated by Excel.
primers <- fread("round1primers-8barcodes.txt",
                      header=TRUE, stringsAsFactors = FALSE, data.table=FALSE) %>%
  filter(initial7F!="")

# Generate all combinations of F barcodes
# and calculate the minimum distance between pairs of barcodes.
indexFcombns <- as.data.frame(t(combn(primers$initial7F, 2)))
minFdistance <- min(sapply(seq(1:nrow(indexFcombns)), 
       function(x) DNABarcodes::distance(indexFcombns$V1[x],indexFcombns$V2[x],"hamming")))

# Generate all combinations of R barcodes
# and calculate the minimum distance between pairs of barcodes.
indexRcombns <- as.data.frame(t(combn(primers$initial7R, 2)))
minRdistance <- min(sapply(seq(1:nrow(indexRcombns)), 
                           function(x) DNABarcodes::distance(indexRcombns$V1[x],indexRcombns$V2[x],"hamming")))

# Count the number of distinct bases at each position in the first 11 bases.
tallydiversity <- primers %>%
  # Split strings containing initial bases.
  separate(initial11F, remove=FALSE,
           into=sapply(seq(1:11), function(x) paste0("F",x)), sep=c(1:10)) %>%
  separate(initial11R, remove=FALSE,
           into=sapply(seq(1:11), function(x) paste0("R",x)), sep=c(1:10)) %>%
  dplyr::select(c(sapply(seq(1:11), function(x) paste0("F",x)),
                sapply(seq(1:11), function(x) paste0("R",x)))) %>%
  gather(base, identity) %>%
  group_by(base) %>%
  filter(identity %in% c("G","T","C","A")) %>%
  summarize(nbases=n_distinct(identity)) %>%
  ungroup() %>% count(nbases, name="npositions")
