executor: slurm

jobs: 100

use-singularity: True

printshellcmds: True
keep-going: True
rerun-incomplete: True

latency-wait: 60

default-resources:
  - mem_mb=4000
  - runtime=60
  - disk_mb=1000

singularity-args: "--cleanenv"